version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-init-tester"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jofksnx4ss9z"
s3_prefix = "node-init-tester"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
